project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex1.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex2.qmd
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

