project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1A
            href: Hands-on_Ex/Hands-on_Ex1A/Hands-on_Ex1A.html
          - text: Hands-on Exercise 1B
            href: Hands-on_Ex/Hands-on_Ex1B/Hands-on_Ex1B.html
          - text: Hands-on Exercise 2A
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2A.html
          - text: Hands-on Exercise 2B
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2B.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_Ex2.html
          - text: In-class Exercise 3
            href: In-class_Ex/In-class_Ex3/In-class_Ex3.html
      - text: Take-home Exercise
        menu: 
          - text: Take-home Exercise 1
          - text: Take-home Exercise 2
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

