<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ISSS624 - Hands-on Exercise 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ISSS624</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="./Hands-on_Ex1.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Hands-on_Ex2.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="./In-class_Ex/In-class_Ex1/In-class_Ex1.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li class="dropdown-header">In-class Exercise 2</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#geospatial-data-wrangling-with-r" id="toc-geospatial-data-wrangling-with-r" class="nav-link active" data-scroll-target="#geospatial-data-wrangling-with-r">1 Geospatial Data Wrangling with R</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">1.1 Overview</a></li>
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition">1.2 Data Acquisition</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">1.3 Getting Started</a></li>
  <li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data">1.4 Importing Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-polygon-feature-data-in-shapefile-format---master-plan-subzone-boundary" id="toc-importing-polygon-feature-data-in-shapefile-format---master-plan-subzone-boundary" class="nav-link" data-scroll-target="#importing-polygon-feature-data-in-shapefile-format---master-plan-subzone-boundary">1.4.1 Importing Polygon Feature Data in shapefile Format - Master Plan Subzone Boundary</a></li>
  <li><a href="#importing-polyline-feature-data-in-shapefile-format---cycling-path" id="toc-importing-polyline-feature-data-in-shapefile-format---cycling-path" class="nav-link" data-scroll-target="#importing-polyline-feature-data-in-shapefile-format---cycling-path">1.4.2 Importing Polyline Feature Data in shapefile Format - Cycling Path</a></li>
  <li><a href="#importing-gis-data-in-kml-format---pre-schools-location" id="toc-importing-gis-data-in-kml-format---pre-schools-location" class="nav-link" data-scroll-target="#importing-gis-data-in-kml-format---pre-schools-location">1.4.3 Importing GIS Data in kml Format - Pre-Schools Location</a></li>
  </ul></li>
  <li><a href="#checking-the-content-of-a-simple-feature-data-frame" id="toc-checking-the-content-of-a-simple-feature-data-frame" class="nav-link" data-scroll-target="#checking-the-content-of-a-simple-feature-data-frame">1.5 Checking the Content of A Simple Feature Data Frame</a>
  <ul class="collapse">
  <li><a href="#master-plan-subzone-boundary" id="toc-master-plan-subzone-boundary" class="nav-link" data-scroll-target="#master-plan-subzone-boundary">1.5.1 Master Plan Subzone Boundary</a></li>
  <li><a href="#cycling-path" id="toc-cycling-path" class="nav-link" data-scroll-target="#cycling-path">1.5.2 Cycling Path</a></li>
  <li><a href="#pre-schools-location" id="toc-pre-schools-location" class="nav-link" data-scroll-target="#pre-schools-location">1.5.3 Pre-Schools Location</a></li>
  </ul></li>
  <li><a href="#plotting-the-geospatial-data" id="toc-plotting-the-geospatial-data" class="nav-link" data-scroll-target="#plotting-the-geospatial-data">1.6 Plotting the Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#master-plan-subzone-boundary-1" id="toc-master-plan-subzone-boundary-1" class="nav-link" data-scroll-target="#master-plan-subzone-boundary-1">1.6.1 Master Plan Subzone Boundary</a></li>
  <li><a href="#cycling-path-1" id="toc-cycling-path-1" class="nav-link" data-scroll-target="#cycling-path-1">1.6.2 Cycling Path</a></li>
  <li><a href="#pre-schools-location-1" id="toc-pre-schools-location-1" class="nav-link" data-scroll-target="#pre-schools-location-1">1.6.3 Pre-Schools Location</a></li>
  </ul></li>
  <li><a href="#working-with-projection" id="toc-working-with-projection" class="nav-link" data-scroll-target="#working-with-projection">1.7 Working with Projection</a>
  <ul class="collapse">
  <li><a href="#assigning-epsg-code-to-a-simple-feature-data-frame" id="toc-assigning-epsg-code-to-a-simple-feature-data-frame" class="nav-link" data-scroll-target="#assigning-epsg-code-to-a-simple-feature-data-frame">1.7.1 Assigning EPSG Code to A Simple Feature Data Frame</a></li>
  <li><a href="#transforming-the-projection-of-pre-schools-location-from-wgs84-to-svy21" id="toc-transforming-the-projection-of-pre-schools-location-from-wgs84-to-svy21" class="nav-link" data-scroll-target="#transforming-the-projection-of-pre-schools-location-from-wgs84-to-svy21">1.7.2 Transforming the Projection of Pre-Schools Location from wgs84 to svy21</a></li>
  </ul></li>
  <li><a href="#importing-and-converting-an-aspatial-data" id="toc-importing-and-converting-an-aspatial-data" class="nav-link" data-scroll-target="#importing-and-converting-an-aspatial-data">1.8 Importing and Converting An Aspatial Data</a></li>
  <li><a href="#geoprocessing-with-sf-package" id="toc-geoprocessing-with-sf-package" class="nav-link" data-scroll-target="#geoprocessing-with-sf-package">1.9 Geoprocessing with sf Package</a>
  <ul class="collapse">
  <li><a href="#buffer-for-cycling-path" id="toc-buffer-for-cycling-path" class="nav-link" data-scroll-target="#buffer-for-cycling-path">1.9.1 Buffer for Cycling Path</a></li>
  <li><a href="#point-in-polygon-count-for-pre-schools" id="toc-point-in-polygon-count-for-pre-schools" class="nav-link" data-scroll-target="#point-in-polygon-count-for-pre-schools">1.9.2 Point-in-Polygon Count for Pre-Schools</a></li>
  <li><a href="#point-in-polygon-count-for-airbnb-listings" id="toc-point-in-polygon-count-for-airbnb-listings" class="nav-link" data-scroll-target="#point-in-polygon-count-for-airbnb-listings">1.9.3 Point-in-Polygon Count for AirBnB Listings</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">1.10 Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#histograms-of-frequency-of-pre-schools-density" id="toc-histograms-of-frequency-of-pre-schools-density" class="nav-link" data-scroll-target="#histograms-of-frequency-of-pre-schools-density">1.10.1 Histograms of Frequency of Pre-Schools Density</a></li>
  <li><a href="#scatterplot-of-pre-schools-density-versus-pre-schools-count" id="toc-scatterplot-of-pre-schools-density-versus-pre-schools-count" class="nav-link" data-scroll-target="#scatterplot-of-pre-schools-density-versus-pre-schools-count">1.10.2 Scatterplot of Pre-Schools Density versus Pre-Schools Count</a></li>
  <li><a href="#histograms-of-frequency-of-airbnb-listings-density" id="toc-histograms-of-frequency-of-airbnb-listings-density" class="nav-link" data-scroll-target="#histograms-of-frequency-of-airbnb-listings-density">1.10.3 Histograms of Frequency of AirBnB Listings Density</a></li>
  <li><a href="#scatterplot-of-airbnb-listings-density-versus-airbnb-listings-count" id="toc-scatterplot-of-airbnb-listings-density-versus-airbnb-listings-count" class="nav-link" data-scroll-target="#scatterplot-of-airbnb-listings-density-versus-airbnb-listings-count">1.10.2 Scatterplot of AirBnB Listings Density versus AirBnB Listings Count</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hands-on Exercise 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="geospatial-data-wrangling-with-r" class="level1">
<h1>1 Geospatial Data Wrangling with R</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">1.1 Overview</h2>
<p>In this page, I show how I had completed the Hands-on Exercise 1. It includes the codes used, the graphs obtained as well as the insights gathered.</p>
</section>
<section id="data-acquisition" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition">1.2 Data Acquisition</h2>
<p>The following data sets were used in this hands-on exercise:</p>
<ul>
<li><p><a href="https://beta.data.gov.sg/collections/1708/view">Master Plan 2014 Subzone Boundary (Web)</a> from <a href="https://data.gov.sg/">data.gov.sg</a></p></li>
<li><p><a href="https://beta.data.gov.sg/collections/2064/view">Pre-Schools Location</a> from <a href="https://data.gov.sg/">data.gov.sg</a></p></li>
<li><p><a href="https://datamall.lta.gov.sg/content/dam/datamall/datasets/Geospatial/CyclingPath.zip">Cycling Path</a> from <a href="https://www.mytransport.sg/content/mytransport/home/dataMall.html">LTADataMall</a></p></li>
<li><p>Latest version of <a href="http://data.insideairbnb.com/singapore/sg/singapore/2023-09-23/visualisations/listings.csv">Singapore AirBnB listing</a> data from <a href="http://insideairbnb.com/get-the-data.html">Inside Airbnb</a></p></li>
</ul>
<p>The data sets were placed under two sub-folders: geospatial (Master Plan Subzone Boundary, Pre-Schools Location, and Cycling Path) and aspatial (AirBnB Listing). These two sub-folders are within the data folder of my Hands-on_Ex1 folder.</p>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">1.3 Getting Started</h2>
<p>The two R packages used in this hands-on exercises were:</p>
<ul>
<li><p><strong>sf</strong> for importing, managing, and processing geospatial data, and</p></li>
<li><p><strong>tidyverse</strong> for performing data science tasks such as importing, wrangling, and visualising data.</p></li>
</ul>
<p>They were loaded into the R environment using the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Student Note</em>: This allowed for loading of multiple packages in one line of code.</p>
</section>
<section id="importing-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-geospatial-data">1.4 Importing Geospatial Data</h2>
<p>The <strong>st_read()</strong> (under sf package) was used to import the three geospatial data sets:</p>
<ul>
<li><p><code>MP14_SUBZONE_WEB_PL</code>, a polygon feature layer in ESRI shapefile format;</p></li>
<li><p><code>CyclingPath</code>, a line feature layer in ESRI shapefile format; and</p></li>
<li><p><code>PreSchool</code>, a point feature layer in kml file format.</p></li>
</ul>
<section id="importing-polygon-feature-data-in-shapefile-format---master-plan-subzone-boundary" class="level3">
<h3 class="anchored" data-anchor-id="importing-polygon-feature-data-in-shapefile-format---master-plan-subzone-boundary">1.4.1 Importing Polygon Feature Data in shapefile Format - Master Plan Subzone Boundary</h3>
<p>The <code>MP14_SUBZONE_WEB_PL</code> data set was imported into R as a polygon feature data frame using <strong>st_read()</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"Hands-on_Ex1/data/geospatial"</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">layer =</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `C:\jmphosis\ISSS624\Hands-on_Ex1\data\geospatial' using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source    
  `C:\jmphosis\ISSS624\Hands-on_Ex1\data\geospatial'    
  using driver `ESRI Shapefile' 
Simple feature collection with 323 features and 15 fields 
Geometry type: MULTIPOLYGON 
Dimension:     XY 
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33 Projected CRS: SVY21</code></pre>
<p><em>Student Note</em>: The geospatial objects are multipolygon features. There are a total of <strong>323 features and 15 fields</strong> in <code>mpsz</code> simple feature data frame. <code>mpsz</code> is in <strong>svy21 projected coordinate system</strong>. The bounding box provides the x extend and y extend of the data.</p>
</section>
<section id="importing-polyline-feature-data-in-shapefile-format---cycling-path" class="level3">
<h3 class="anchored" data-anchor-id="importing-polyline-feature-data-in-shapefile-format---cycling-path">1.4.2 Importing Polyline Feature Data in shapefile Format - Cycling Path</h3>
<p>The <code>CyclingPath</code> data set was imported into R as a line feature data frame using st_read().</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cyclingpath <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"Hands-on_Ex1/data/geospatial"</span>, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">layer =</span> <span class="st">"CyclingPathGazette"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `CyclingPathGazette' from data source 
  `C:\jmphosis\ISSS624\Hands-on_Ex1\data\geospatial' using driver `ESRI Shapefile'
Simple feature collection with 2558 features and 2 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 11854.32 ymin: 28347.98 xmax: 42626.09 ymax: 48948.15
Projected CRS: SVY21</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Reading layer `CyclingPathGazette' from data source    
  `C:\jmphosis\ISSS624\Hands-on_Ex1\data\geospatial'    
  using driver `ESRI Shapefile' 
Simple feature collection with 2558 features and 2 fields 
Geometry type: MULTILINESTRING 
Dimension:     XY 
Bounding box:  xmin: 11854.32 ymin: 28347.98 xmax: 42626.09 ymax: 48948.15 Projected CRS: SVY21</code></pre>
<p><em>Student Note</em>: The geospatial objects are multistring features. There are a total of <strong>2,558 features and 2 fields</strong> in <code>cyclingpath</code> linestring feature data frame. <code>cyclingpath</code> is in <strong>svy21 projected coordinate system</strong>.</p>
</section>
<section id="importing-gis-data-in-kml-format---pre-schools-location" class="level3">
<h3 class="anchored" data-anchor-id="importing-gis-data-in-kml-format---pre-schools-location">1.4.3 Importing GIS Data in kml Format - Pre-Schools Location</h3>
<p>The <code>PreSchool</code> data set was imported into R as a point feature data frame using st_read(). As it is in the kml format, the file extension is included.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>preschool <span class="ot">=</span> <span class="fu">st_read</span>(<span class="st">"Hands-on_Ex1/data/geospatial/PreSchoolsLocation.kml"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `PRESCHOOLS_LOCATION' from data source 
  `C:\jmphosis\ISSS624\Hands-on_Ex1\data\geospatial\PreSchoolsLocation.kml' 
  using driver `KML'
Simple feature collection with 2290 features and 2 fields
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Reading layer `PRESCHOOLS_LOCATION' from data source 
  `C:\jmphosis\ISSS624\Hands-on_Ex1\data\geospatial\PreSchoolsLocation.kml' 
  using driver `KML'
Simple feature collection with 2290 features and 2 fields
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84</code></pre>
<p><em>Student Note</em>: The geospatial objects are point features. There are a total of <strong>2,290 features and 2 fields</strong> in <code>preschool</code> point feature data frame. <code>preschool</code> is in <strong>wgs84 coordinate system</strong>.</p>
</section>
</section>
<section id="checking-the-content-of-a-simple-feature-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-content-of-a-simple-feature-data-frame">1.5 Checking the Content of A Simple Feature Data Frame</h2>
<p>The following ways to retrieve information related to the content of a simple feature data frame were applied on the three data frames: <code>mpsz</code>, <code>cyclingpath</code>, and <code>preschool</code>:</p>
<ul>
<li><p><strong>st_geometry()</strong> (under sf package) retrieves the geometries from an object.</p></li>
<li><p><strong>glimpse()</strong> (under dplyr package) retrieves information about the associated attributes in the data frame.</p></li>
<li><p><strong>head()</strong> (under Base R) reveals complete information of a feature object.</p></li>
</ul>
<section id="master-plan-subzone-boundary" class="level3">
<h3 class="anchored" data-anchor-id="master-plan-subzone-boundary">1.5.1 Master Plan Subzone Boundary</h3>
<p>The three functions were applied to <code>mpsz</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 323 features 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((31495.56 30140.01, 31980.96 296...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29092.28 30021.89, 29119.64 300...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((29932.33 29879.12, 29947.32 298...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((27131.28 30059.73, 27088.33 297...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((26451.03 30396.46, 26440.47 303...</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Geometry set for 323 features  
Geometry type: MULTIPOLYGON 
Dimension:     XY 
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33 Projected CRS: SVY21 
First 5 geometries: 
MULTIPOLYGON (((31495.56 30140.01, 31980.96 296... 
MULTIPOLYGON (((29092.28 30021.89, 29119.64 300... 
MULTIPOLYGON (((29932.33 29879.12, 29947.32 298... 
MULTIPOLYGON (((27131.28 30059.73, 27088.33 297... 
MULTIPOLYGON (((26451.03 30396.46, 26440.47 303...</code></pre>
<p><em>Student Note</em>: The above shows that <code>mpsz</code> is a multipolygon feature object and in the svy21 projected coordinates systems.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 323
Columns: 16
$ OBJECTID   &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …
$ SUBZONE_NO &lt;int&gt; 1, 1, 3, 8, 3, 7, 9, 2, 13, 7, 12, 6, 1, 5, 1, 1, 3, 2, 2, …
$ SUBZONE_N  &lt;chr&gt; "MARINA SOUTH", "PEARL'S HILL", "BOAT QUAY", "HENDERSON HIL…
$ SUBZONE_C  &lt;chr&gt; "MSSZ01", "OTSZ01", "SRSZ03", "BMSZ08", "BMSZ03", "BMSZ07",…
$ CA_IND     &lt;chr&gt; "Y", "Y", "Y", "N", "N", "N", "N", "Y", "N", "N", "N", "N",…
$ PLN_AREA_N &lt;chr&gt; "MARINA SOUTH", "OUTRAM", "SINGAPORE RIVER", "BUKIT MERAH",…
$ PLN_AREA_C &lt;chr&gt; "MS", "OT", "SR", "BM", "BM", "BM", "BM", "SR", "QT", "QT",…
$ REGION_N   &lt;chr&gt; "CENTRAL REGION", "CENTRAL REGION", "CENTRAL REGION", "CENT…
$ REGION_C   &lt;chr&gt; "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR", "CR",…
$ INC_CRC    &lt;chr&gt; "5ED7EB253F99252E", "8C7149B9EB32EEFC", "C35FEFF02B13E0E5",…
$ FMEL_UPD_D &lt;date&gt; 2014-12-05, 2014-12-05, 2014-12-05, 2014-12-05, 2014-12-05…
$ X_ADDR     &lt;dbl&gt; 31595.84, 28679.06, 29654.96, 26782.83, 26201.96, 25358.82,…
$ Y_ADDR     &lt;dbl&gt; 29220.19, 29782.05, 29974.66, 29933.77, 30005.70, 29991.38,…
$ SHAPE_Leng &lt;dbl&gt; 5267.381, 3506.107, 1740.926, 3313.625, 2825.594, 4428.913,…
$ SHAPE_Area &lt;dbl&gt; 1630379.27, 559816.25, 160807.50, 595428.89, 387429.44, 103…
$ geometry   &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((31495.56 30..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Rows: 323 
Columns: 16 
$ OBJECTID   &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12… 
$ SUBZONE_NO &lt;int&gt; 1, 1, 3, 8, 3, 7, 9, 2, 13, 7, 12, 6,… 
$ SUBZONE_N  &lt;chr&gt; "MARINA SOUTH", "PEARL'S HILL", "BOAT… 
$ SUBZONE_C  &lt;chr&gt; "MSSZ01", "OTSZ01", "SRSZ03", "BMSZ08… 
$ CA_IND     &lt;chr&gt; "Y", "Y", "Y", "N", "N", "N", "N", "Y… 
$ PLN_AREA_N &lt;chr&gt; "MARINA SOUTH", "OUTRAM", "SINGAPORE … 
$ PLN_AREA_C &lt;chr&gt; "MS", "OT", "SR", "BM", "BM", "BM", "… 
$ REGION_N   &lt;chr&gt; "CENTRAL REGION", "CENTRAL REGION", "… 
$ REGION_C   &lt;chr&gt; "CR", "CR", "CR", "CR", "CR", "CR", "… 
$ INC_CRC    &lt;chr&gt; "5ED7EB253F99252E", "8C7149B9EB32EEFC… 
$ FMEL_UPD_D &lt;date&gt; 2014-12-05, 2014-12-05, 2014-12-05, … 
$ X_ADDR     &lt;dbl&gt; 31595.84, 28679.06, 29654.96, 26782.8… 
$ Y_ADDR     &lt;dbl&gt; 29220.19, 29782.05, 29974.66, 29933.7… 
$ SHAPE_Leng &lt;dbl&gt; 5267.381, 3506.107, 1740.926, 3313.62… 
$ SHAPE_Area &lt;dbl&gt; 1630379.3, 559816.2, 160807.5, 595428… 
$ geometry   &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((31495.56…</code></pre>
<p><em>Student Note</em>: The above shows the data type of each field and some examples of the values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mpsz, <span class="at">n=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 5 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 25867.68 ymin: 28369.47 xmax: 32362.39 ymax: 30435.54
Projected CRS: SVY21
  OBJECTID SUBZONE_NO      SUBZONE_N SUBZONE_C CA_IND      PLN_AREA_N
1        1          1   MARINA SOUTH    MSSZ01      Y    MARINA SOUTH
2        2          1   PEARL'S HILL    OTSZ01      Y          OUTRAM
3        3          3      BOAT QUAY    SRSZ03      Y SINGAPORE RIVER
4        4          8 HENDERSON HILL    BMSZ08      N     BUKIT MERAH
5        5          3        REDHILL    BMSZ03      N     BUKIT MERAH
  PLN_AREA_C       REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR
1         MS CENTRAL REGION       CR 5ED7EB253F99252E 2014-12-05 31595.84
2         OT CENTRAL REGION       CR 8C7149B9EB32EEFC 2014-12-05 28679.06
3         SR CENTRAL REGION       CR C35FEFF02B13E0E5 2014-12-05 29654.96
4         BM CENTRAL REGION       CR 3775D82C5DDBEFBD 2014-12-05 26782.83
5         BM CENTRAL REGION       CR 85D9ABEF0A40678F 2014-12-05 26201.96
    Y_ADDR SHAPE_Leng SHAPE_Area                       geometry
1 29220.19   5267.381  1630379.3 MULTIPOLYGON (((31495.56 30...
2 29782.05   3506.107   559816.2 MULTIPOLYGON (((29092.28 30...
3 29974.66   1740.926   160807.5 MULTIPOLYGON (((29932.33 29...
4 29933.77   3313.625   595428.9 MULTIPOLYGON (((27131.28 30...
5 30005.70   2825.594   387429.4 MULTIPOLYGON (((26451.03 30...</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Simple feature collection with 5 features and 15 fields 
Geometry type: MULTIPOLYGON 
Dimension:     XY 
Bounding box:  xmin: 25867.68 ymin: 28369.47 xmax: 32362.39 ymax: 30435.54 Projected CRS: SVY21   
OBJECTID SUBZONE_NO      SUBZONE_N SUBZONE_C CA_IND 
1        1          1   MARINA SOUTH    MSSZ01      Y 
2        2          1   PEARL'S HILL    OTSZ01      Y 
3        3          3      BOAT QUAY    SRSZ03      Y 
4        4          8 HENDERSON HILL    BMSZ08      N 
5        5          3        REDHILL    BMSZ03      N
PLN_AREA_N PLN_AREA_C       REGION_N REGION_C 
1    MARINA SOUTH         MS CENTRAL REGION       CR 
2          OUTRAM         OT CENTRAL REGION       CR 
3 SINGAPORE RIVER         SR CENTRAL REGION       CR 
4     BUKIT MERAH         BM CENTRAL REGION       CR 
5     BUKIT MERAH         BM CENTRAL REGION       CR
INC_CRC FMEL_UPD_D   X_ADDR   Y_ADDR 
1 5ED7EB253F99252E 2014-12-05 31595.84 29220.19 
2 8C7149B9EB32EEFC 2014-12-05 28679.06 29782.05 
3 C35FEFF02B13E0E5 2014-12-05 29654.96 29974.66 
4 3775D82C5DDBEFBD 2014-12-05 26782.83 29933.77 
5 85D9ABEF0A40678F 2014-12-05 26201.96 30005.70   
SHAPE_Leng SHAPE_Area                       geometry 
1   5267.381  1630379.3 MULTIPOLYGON (((31495.56 30... 
2   3506.107   559816.2 MULTIPOLYGON (((29092.28 30... 
3   1740.926   160807.5 MULTIPOLYGON (((29932.33 29... 
4   3313.625   595428.9 MULTIPOLYGON (((27131.28 30... 
5   2825.594   387429.4 MULTIPOLYGON (((26451.03 30...</code></pre>
<p><em>Student Note</em>: The above shows the first 5 records in <code>mpsz</code>.</p>
</section>
<section id="cycling-path" class="level3">
<h3 class="anchored" data-anchor-id="cycling-path">1.5.2 Cycling Path</h3>
<p>The three functions were applied to <code>cyclingpath</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(cyclingpath)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 2558 features 
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 11854.32 ymin: 28347.98 xmax: 42626.09 ymax: 48948.15
Projected CRS: SVY21
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTILINESTRING ((39782.85 34832.11, 39799.44 3...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTILINESTRING ((39931.51 35100.96, 39827.86 3...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTILINESTRING ((40031.89 35124.94, 39977.14 3...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTILINESTRING ((39958.38 37075.99, 40010.3 37...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTILINESTRING ((39652.87 36751.62, 39648.35 3...</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Geometry set for 2558 features 
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 11854.32 ymin: 28347.98 xmax: 42626.09 ymax: 48948.15
Projected CRS: SVY21
First 5 geometries:
MULTILINESTRING ((39782.85 34832.11, 39799.44 3...
MULTILINESTRING ((39931.51 35100.96, 39827.86 3...
MULTILINESTRING ((40031.89 35124.94, 39977.14 3...
MULTILINESTRING ((39958.38 37075.99, 40010.3 37...
MULTILINESTRING ((39652.87 36751.62, 39648.35 3...</code></pre>
<p><em>Student Note</em>: The above shows that <code>cyclingpath</code> is a multilinestring feature object and in the svy21 projected coordinates systems.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(cyclingpath)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,558
Columns: 3
$ PLANNING_A &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ PLANNING_1 &lt;chr&gt; "BEDOK", "BEDOK", "BEDOK", "TAMPINES", "TAMPINES", "TAMPINE…
$ geometry   &lt;MULTILINESTRING [m]&gt; MULTILINESTRING ((39782.85 ..., MULTILINEST…</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Rows: 2,558
Columns: 3
$ PLANNING_A &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ PLANNING_1 &lt;chr&gt; "BEDOK", "BEDOK", "BEDOK", "TAMPINES", "TAMPINES", "TAMPINES", "TAMPINES", "TAMPINES", "YISHUN", "T…
$ geometry   &lt;MULTILINESTRING [m]&gt; MULTILINESTRING ((39782.85 ..., MULTILINESTRING ((39931.51 ..., MULTILINESTRING ((4…</code></pre>
<p><em>Student Note</em>: The above shows the data type of each field and some examples of the values. The PLANNING_A column appears to only have ‘NA’ values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cyclingpath, <span class="at">n=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 5 features and 2 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 39598.41 ymin: 34811.14 xmax: 40031.89 ymax: 37075.99
Projected CRS: SVY21
  PLANNING_A PLANNING_1                       geometry
1       &lt;NA&gt;      BEDOK MULTILINESTRING ((39782.85 ...
2       &lt;NA&gt;      BEDOK MULTILINESTRING ((39931.51 ...
3       &lt;NA&gt;      BEDOK MULTILINESTRING ((40031.89 ...
4       &lt;NA&gt;   TAMPINES MULTILINESTRING ((39958.38 ...
5       &lt;NA&gt;   TAMPINES MULTILINESTRING ((39652.87 ...</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Simple feature collection with 5 features and 2 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 39598.41 ymin: 34811.14 xmax: 40031.89 ymax: 37075.99
Projected CRS: SVY21
  PLANNING_A PLANNING_1                       geometry
1       &lt;NA&gt;      BEDOK MULTILINESTRING ((39782.85 ...
2       &lt;NA&gt;      BEDOK MULTILINESTRING ((39931.51 ...
3       &lt;NA&gt;      BEDOK MULTILINESTRING ((40031.89 ...
4       &lt;NA&gt;   TAMPINES MULTILINESTRING ((39958.38 ...
5       &lt;NA&gt;   TAMPINES MULTILINESTRING ((39652.87 ...</code></pre>
<p><em>Student Note</em>: The above shows the first 5 records in <code>cyclingpath</code>.</p>
</section>
<section id="pre-schools-location" class="level3">
<h3 class="anchored" data-anchor-id="pre-schools-location">1.5.3 Pre-Schools Location</h3>
<p>The three functions were applied to <code>preschool</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(preschool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 2290 features 
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (103.8072 1.299333 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (103.826 1.312839 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (103.8409 1.348843 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (103.8048 1.435024 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (103.839 1.33315 0)</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Geometry set for 2290 features 
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84
First 5 geometries:
POINT Z (103.8072 1.299333 0)
POINT Z (103.826 1.312839 0)
POINT Z (103.8409 1.348843 0)
POINT Z (103.8048 1.435024 0)
POINT Z (103.839 1.33315 0)</code></pre>
<p><em>Student Note</em>: The above shows that <code>preschool</code> is a point feature object and in the wgs84 coordinates systems.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(preschool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,290
Columns: 3
$ Name        &lt;chr&gt; "kml_1", "kml_2", "kml_3", "kml_4", "kml_5", "kml_6", "kml…
$ Description &lt;chr&gt; "&lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Att…
$ geometry    &lt;POINT [°]&gt; POINT Z (103.8072 1.299333 0), POINT Z (103.826 1.31…</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Rows: 2,290
Columns: 3
$ Name        &lt;chr&gt; "kml_1", "kml_2", "kml_3", "kml_4", "kml_5", "kml_6", "kml_7", "kml_8", "kml_9", "kml_10", "kml_11…
$ Description &lt;chr&gt; "&lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor=\"#E3E…
$ geometry    &lt;POINT [°]&gt; POINT Z (103.8072 1.299333 0), POINT Z (103.826 1.312839 0), POINT Z (103.8409 1.348843 0), …</code></pre>
<p><em>Student Note</em>: The above shows the data type of each field and some examples of the values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(preschool, <span class="at">n=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 5 features and 2 fields
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.8048 ymin: 1.299333 xmax: 103.8409 ymax: 1.435024
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84
   Name
1 kml_1
2 kml_2
3 kml_3
4 kml_4
5 kml_5
                                                                                                                                                                                                                                                                                                                                                                                                Description
1           &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDREN'S COVE PRESCHOOL PTE.LTD.&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT9390&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;498CC9FE48CC94D4&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
2                    &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDREN'S COVE PTE. LTD.&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT8675&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;22877550804213FD&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
3       &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDREN'S VINEYARD PRESCHOOL PTE. LTD&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT9308&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;B2FE90E44AD494E3&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
4 &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDTIME CARE &amp; DEVELOPMENT CENTRE PTE.LTD.&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT9122&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;1384CDC0D14B76A1&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
5                               &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILTERN HOUSE&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT2070&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;FB24EAA6E73B2723&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
                       geometry
1 POINT Z (103.8072 1.299333 0)
2  POINT Z (103.826 1.312839 0)
3 POINT Z (103.8409 1.348843 0)
4 POINT Z (103.8048 1.435024 0)
5   POINT Z (103.839 1.33315 0)</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Simple feature collection with 5 features and 2 fields
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 103.8048 ymin: 1.299333 xmax: 103.8409 ymax: 1.435024
z_range:       zmin: 0 zmax: 0
Geodetic CRS:  WGS 84
   Name
1 kml_1
2 kml_2
3 kml_3
4 kml_4
5 kml_5
                                                                                   Description
1           &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDREN'S COVE PRESCHOOL PTE.LTD.&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT9390&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;498CC9FE48CC94D4&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
2                    &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDREN'S COVE PTE. LTD.&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT8675&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;22877550804213FD&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
3       &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDREN'S VINEYARD PRESCHOOL PTE. LTD&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT9308&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;B2FE90E44AD494E3&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
4 &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILDTIME CARE &amp; DEVELOPMENT CENTRE PTE.LTD.&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT9122&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;1384CDC0D14B76A1&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
5                               &lt;center&gt;&lt;table&gt;&lt;tr&gt;&lt;th colspan='2' align='center'&gt;&lt;em&gt;Attributes&lt;/em&gt;&lt;/th&gt;&lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;CENTRE_NAME&lt;/th&gt; &lt;td&gt;CHILTERN HOUSE&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;CENTRE_CODE&lt;/th&gt; &lt;td&gt;PT2070&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor="#E3E3F3"&gt; &lt;th&gt;INC_CRC&lt;/th&gt; &lt;td&gt;FB24EAA6E73B2723&lt;/td&gt; &lt;/tr&gt;&lt;tr bgcolor=""&gt; &lt;th&gt;FMEL_UPD_D&lt;/th&gt; &lt;td&gt;20211201093631&lt;/td&gt; &lt;/tr&gt;&lt;/table&gt;&lt;/center&gt;
                       geometry
1 POINT Z (103.8072 1.299333 0)
2  POINT Z (103.826 1.312839 0)
3 POINT Z (103.8409 1.348843 0)
4 POINT Z (103.8048 1.435024 0)
5   POINT Z (103.839 1.33315 0)</code></pre>
<p><em>Student Note</em>: The above shows the first 5 records in <code>preschool</code>.</p>
</section>
</section>
<section id="plotting-the-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="plotting-the-geospatial-data">1.6 Plotting the Geospatial Data</h2>
<p>The <strong>plot()</strong> (under R graphics) was used to visualise the geospatial features of the three data frames: <code>mpsz</code>, <code>cyclingpath</code>, and <code>preschool</code>.</p>
<section id="master-plan-subzone-boundary-1" class="level3">
<h3 class="anchored" data-anchor-id="master-plan-subzone-boundary-1">1.6.1 Master Plan Subzone Boundary</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: plotting the first 9 out of 15 attributes; use max.plot = 15 to plot
all</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(mpsz))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz[<span class="st">"PLN_AREA_N"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="cycling-path-1" class="level3">
<h3 class="anchored" data-anchor-id="cycling-path-1">1.6.2 Cycling Path</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(cyclingpath))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cyclingpath[<span class="st">"PLANNING_1"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="pre-schools-location-1" class="level3">
<h3 class="anchored" data-anchor-id="pre-schools-location-1">1.6.3 Pre-Schools Location</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(preschool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(preschool))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="working-with-projection" class="level2">
<h2 class="anchored" data-anchor-id="working-with-projection">1.7 Working with Projection</h2>
<p>It is essential for two geospatial data objects to be projected using similar coordinate systems. In the hands-on exercise, we projected a simple feature data frame from one coordinate system to another through <strong>projection transformation</strong>.</p>
<section id="assigning-epsg-code-to-a-simple-feature-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="assigning-epsg-code-to-a-simple-feature-data-frame">1.7.1 Assigning EPSG Code to A Simple Feature Data Frame</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: SVY21 
  wkt:
PROJCRS["SVY21",
    BASEGEOGCRS["SVY21[WGS84]",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]</code></pre>
</div>
</div>
<pre><code>Coordinate Reference System:   
User input: SVY21    
wkt: 
PROJCRS["SVY21",
    BASEGEOGCRS["SVY21[WGS84]",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,                 
                LENGTHUNIT["metre",1]],             
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,             
            ANGLEUNIT["Degree",0.0174532925199433]]],     
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,                 
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,             
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1], 
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642, 
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572, 
            LENGTHUNIT["metre",1], 
            ID["EPSG",8807]]], 
    CS[Cartesian,2],
        AXIS["(E)",east, 
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north
            ORDER[2], 
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]</code></pre>
<p>The above shows that the <code>mpsz</code> data frame has the wrong EPSG code (9001). Hence, the st_set_crs() (under sf package) is used to assign the correct EPSG code (3414).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>mpsz3414 <span class="ot">=</span> <span class="fu">st_set_crs</span>(mpsz, <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: st_crs&lt;- : replacing crs does not reproject data; use st_transform for
that</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz3414)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
<pre><code>Coordinate Reference System:   
User input: EPSG:3414    
wkt: 
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21", 
            ELLIPSOID["WGS 84",6378137,298.257223563,                 
                LENGTHUNIT["metre",1]]], 
        PRIMEM["Greenwich",0, 
            ANGLEUNIT["degree",0.0174532925199433]], 
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator", 
            ID["EPSG",9807]], 
        PARAMETER["Latitude of natural origin",1.36666666666667,             
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,             
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642, 
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north, 
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],         
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</section>
<section id="transforming-the-projection-of-pre-schools-location-from-wgs84-to-svy21" class="level3">
<h3 class="anchored" data-anchor-id="transforming-the-projection-of-pre-schools-location-from-wgs84-to-svy21">1.7.2 Transforming the Projection of Pre-Schools Location from wgs84 to svy21</h3>
<p>In geospatial analytics, data in the geographic coordinate system are often transformed to the projected coordinate system. This allows analysis based on measurements such as distance and area.</p>
<p>The st_transform() (under sf package) is required when the coordinate system needs to be transformed (and not just a matter of changing the EPSG code).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>preschool3414 <span class="ot">=</span> <span class="fu">st_transform</span>(preschool, </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(preschool3414)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 2290 features 
Geometry type: POINT
Dimension:     XYZ
Bounding box:  xmin: 11810.03 ymin: 25596.33 xmax: 45404.24 ymax: 49300.88
z_range:       zmin: 0 zmax: 0
Projected CRS: SVY21 / Singapore TM
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (25089.46 31299.16 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (27189.07 32792.54 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (28844.56 36773.76 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (24821.92 46303.16 0)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>POINT Z (28637.82 35038.49 0)</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Geometry set for 2290 features  
Geometry type: POINT 
Dimension:     XYZ 
Bounding box:  xmin: 11810.03 ymin: 25596.33 xmax: 45404.24 ymax: 49300.88 
z_range:       zmin: 0 zmax: 0 
Projected CRS: SVY21 / Singapore TM 
First 5 geometries: 
POINT Z (25089.46 31299.16 0) 
POINT Z (27189.07 32792.54 0) 
POINT Z (28844.56 36773.76 0) 
POINT Z (24821.92 46303.16 0) 
POINT Z (28637.82 35038.49 0)</code></pre>
</section>
</section>
<section id="importing-and-converting-an-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-and-converting-an-aspatial-data">1.8 Importing and Converting An Aspatial Data</h2>
<p>Aspatial data are not geospatial data but have data fields that capture the x- and y-coordinates of the data points.</p>
<p>The AirBnB listing aspatial data is imported into the R environment as a tibble data frame, and converted to a simple feature data frame.</p>
<p>The csv file is imported using <strong>read_csv()</strong> (under readr package) as a tibble data frame. Then, a quick check is conducted on the imported data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>listings <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"Hands-on_Ex1/data/aspatial/listings.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 3483 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (6): name, host_name, neighbourhood_group, neighbourhood, room_type, l...
dbl  (11): id, host_id, latitude, longitude, price, minimum_nights, number_o...
date  (1): last_review

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(listings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 3,483 × 18
       id name      host_id host_name neighbourhood_group neighbourhood latitude
    &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;               &lt;chr&gt;            &lt;dbl&gt;
 1  71609 Villa in…  367042 Belinda   East Region         Tampines          1.35
 2  71896 Home in …  367042 Belinda   East Region         Tampines          1.35
 3  71903 Home in …  367042 Belinda   East Region         Tampines          1.35
 4 275343 Rental u… 1439258 Kay       Central Region      Bukit Merah       1.29
 5 275344 Rental u… 1439258 Kay       Central Region      Bukit Merah       1.29
 6 289234 Home in …  367042 Belinda   East Region         Tampines          1.34
 7 294281 Rental u… 1521514 Elizabeth Central Region      Newton            1.31
 8 324945 Rental u… 1439258 Kay       Central Region      Bukit Merah       1.29
 9 330095 Rental u… 1439258 Kay       Central Region      Bukit Merah       1.29
10 369141 Place to… 1521514 Elizabeth Central Region      Newton            1.31
# ℹ 3,473 more rows
# ℹ 11 more variables: longitude &lt;dbl&gt;, room_type &lt;chr&gt;, price &lt;dbl&gt;,
#   minimum_nights &lt;dbl&gt;, number_of_reviews &lt;dbl&gt;, last_review &lt;date&gt;,
#   reviews_per_month &lt;dbl&gt;, calculated_host_listings_count &lt;dbl&gt;,
#   availability_365 &lt;dbl&gt;, number_of_reviews_ltm &lt;dbl&gt;, license &lt;chr&gt;</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>[[1]] 
# A tibble: 3,483 × 18
      id name        host_id host_name neighbourhood_group neighbourhood     
      &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;               &lt;chr&gt;          
1  71609 Villa in S…  367042 Belinda   East Region         Tampines       
2  71896 Home in Si…  367042 Belinda   East Region         Tampines       
3  71903 Home in Si…  367042 Belinda   East Region         Tampines       
4 275343 Rental uni… 1439258 Kay       Central Region      Bukit Merah    
5 275344 Rental uni… 1439258 Kay       Central Region      Bukit Merah    
6 289234 Home in Si…  367042 Belinda   East Region         Tampines       
7 294281 Rental uni… 1521514 Elizabeth Central Region      Newton         
8 324945 Rental uni… 1439258 Kay       Central Region      Bukit Merah    
9 330095 Rental uni… 1439258 Kay       Central Region      Bukit Merah   
10 369141 Place to s… 1521514 Elizabeth Central Region      Newton        
# ℹ 3,473 more rows
# ℹ 12 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, room_type &lt;chr&gt;, 
#   price &lt;dbl&gt;, minimum_nights &lt;dbl&gt;, number_of_reviews &lt;dbl&gt;, 
#   last_review &lt;date&gt;, reviews_per_month &lt;dbl&gt;, 
#   calculated_host_listings_count &lt;dbl&gt;, availability_365 &lt;dbl&gt;, 
#   number_of_reviews_ltm &lt;dbl&gt;, license &lt;chr&gt; 
# ℹ Use `print(n = ...)` to see more rows</code></pre>
<p><em>Student Note</em>: The <code>listing</code> tibble data frame contains 3,483 rows and 18 columns.</p>
<p>The longitude and latitude columns are used to convert the tibble data frame into a simple feature data frame using <strong>st_as_sf()</strong> (under sf package). Then, the contents of the newly created simple feature data frame, <code>listings_sf</code>, is examined using <strong>glimpse()</strong> (under dplyr package). The longitude and latitude columns have been replaced by a new column, geometry.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>listings_sf <span class="ot">=</span> <span class="fu">st_as_sf</span>(listings,</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(listings_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,483
Columns: 17
$ id                             &lt;dbl&gt; 71609, 71896, 71903, 275343, 275344, 28…
$ name                           &lt;chr&gt; "Villa in Singapore · ★4.44 · 2 bedroom…
$ host_id                        &lt;dbl&gt; 367042, 367042, 367042, 1439258, 143925…
$ host_name                      &lt;chr&gt; "Belinda", "Belinda", "Belinda", "Kay",…
$ neighbourhood_group            &lt;chr&gt; "East Region", "East Region", "East Reg…
$ neighbourhood                  &lt;chr&gt; "Tampines", "Tampines", "Tampines", "Bu…
$ room_type                      &lt;chr&gt; "Private room", "Private room", "Privat…
$ price                          &lt;dbl&gt; 150, 80, 80, 55, 69, 220, 85, 75, 45, 7…
$ minimum_nights                 &lt;dbl&gt; 92, 92, 92, 60, 60, 92, 92, 60, 60, 92,…
$ number_of_reviews              &lt;dbl&gt; 20, 24, 47, 22, 17, 12, 133, 18, 6, 81,…
$ last_review                    &lt;date&gt; 2020-01-17, 2019-10-13, 2020-01-09, 20…
$ reviews_per_month              &lt;dbl&gt; 0.14, 0.16, 0.31, 0.17, 0.12, 0.09, 0.9…
$ calculated_host_listings_count &lt;dbl&gt; 5, 5, 5, 52, 52, 5, 7, 52, 52, 7, 7, 1,…
$ availability_365               &lt;dbl&gt; 89, 89, 89, 275, 274, 89, 365, 365, 365…
$ number_of_reviews_ltm          &lt;dbl&gt; 0, 0, 0, 0, 3, 0, 0, 1, 3, 0, 0, 0, 0, …
$ license                        &lt;chr&gt; NA, NA, NA, "S0399", "S0399", NA, NA, "…
$ geometry                       &lt;POINT [m]&gt; POINT (41972.5 36390.05), POINT (…</code></pre>
</div>
</div>
<p>Outcome:</p>
<pre><code>Rows: 3,483 
Columns: 17 
$ id                             &lt;dbl&gt; 71609, 71896, 71903, 275343, 27… 
$ name                           &lt;chr&gt; "Villa in Singapore · ★4.44 · 2… 
$ host_id                        &lt;dbl&gt; 367042, 367042, 367042, 1439258… 
$ host_name                      &lt;chr&gt; "Belinda", "Belinda", "Belinda"… 
$ neighbourhood_group            &lt;chr&gt; "East Region", "East Region", "… 
$ neighbourhood                  &lt;chr&gt; "Tampines", "Tampines", "Tampin… 
$ room_type                      &lt;chr&gt; "Private room", "Private room",… 
$ price                          &lt;dbl&gt; 150, 80, 80, 55, 69, 220, 85, 7… 
$ minimum_nights                 &lt;dbl&gt; 92, 92, 92, 60, 60, 92, 92, 60,… 
$ number_of_reviews              &lt;dbl&gt; 20, 24, 47, 22, 17, 12, 133, 18… 
$ last_review                    &lt;date&gt; 2020-01-17, 2019-10-13, 2020-0… 
$ reviews_per_month              &lt;dbl&gt; 0.14, 0.16, 0.31, 0.17, 0.12, 0… 
$ calculated_host_listings_count &lt;dbl&gt; 5, 5, 5, 52, 52, 5, 7, 52, 52, … 
$ availability_365               &lt;dbl&gt; 89, 89, 89, 275, 274, 89, 365, … 
$ number_of_reviews_ltm          &lt;dbl&gt; 0, 0, 0, 0, 3, 0, 0, 1, 3, 0, 0… 
$ license                        &lt;chr&gt; NA, NA, NA, "S0399", "S0399", N… 
$ geometry                       &lt;POINT [m]&gt; POINT (41972.5 36390.05),…</code></pre>
</section>
<section id="geoprocessing-with-sf-package" class="level2">
<h2 class="anchored" data-anchor-id="geoprocessing-with-sf-package">1.9 Geoprocessing with sf Package</h2>
<p>The sf package also offers a wide range of geoprocessing (also known as GIS analysis) functions. The following are utilised in this hands-on exercise:</p>
<ul>
<li><p><strong>st_buffer()</strong> creates a buffer around spatial geometries.</p></li>
<li><p><strong>st_area()</strong> calculates the area of spatial geometries.</p></li>
<li><p><strong>st_intersects()</strong> returns a logical vector indicating which geometries in a set intersect with a reference geometry.</p></li>
</ul>
<section id="buffer-for-cycling-path" class="level3">
<h3 class="anchored" data-anchor-id="buffer-for-cycling-path">1.9.1 Buffer for Cycling Path</h3>
<p>Scenario:</p>
<p>The authority is planning to upgrade the existing cycling paths. They need to acuire 5 metres of reserved land on both sides of the paths. Hence, need to find the extent of the land to be acquired and their total area.</p>
<p>Solution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>buffer_cycling <span class="ot">=</span> <span class="fu">st_buffer</span>(cyclingpath,</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">dist=</span><span class="dv">5</span>, <span class="at">nQuadSegs =</span> <span class="dv">30</span>)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>buffer_cycling<span class="sc">$</span>AREA <span class="ot">=</span> <span class="fu">st_area</span>(buffer_cycling)</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(buffer_cycling<span class="sc">$</span>AREA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1774367 [m^2]</code></pre>
</div>
</div>
<p>Answer: <strong>1,774,367 [m^2]</strong></p>
</section>
<section id="point-in-polygon-count-for-pre-schools" class="level3">
<h3 class="anchored" data-anchor-id="point-in-polygon-count-for-pre-schools">1.9.2 Point-in-Polygon Count for Pre-Schools</h3>
<p>Scenario:</p>
<p>A pre-school service group wants to find out the numbers of pre-schools in each Planning Subzone.</p>
<p>Solution:</p>
<p>The st_intersects identify pre-schools in <code>preschool3414</code> that are in each planning subzone of <code>mpsz3414</code>. The <strong>length()</strong> (under Base R) is used to count the number of pre-schools in each planning subzone. The <strong>top_n()</strong> (under dplyr) is used to obtain details of the planning subzone with the most number of preschools.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(mpsz3414, preschool3414))</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00    4.00    7.09   10.00   72.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">top_n</span>(mpsz3414, <span class="dv">1</span>, <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 39655.33 ymin: 35966 xmax: 42940.57 ymax: 38622.37
Projected CRS: SVY21 / Singapore TM
  OBJECTID SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C
1      189          2 TAMPINES EAST    TMSZ02      N   TAMPINES         TM
     REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR   Y_ADDR SHAPE_Leng
1 EAST REGION       ER 21658EAAF84F4D8D 2014-12-05 41122.55 37392.39   10180.62
  SHAPE_Area                       geometry PreSch Count
1    4339824 MULTIPOLYGON (((42196.76 38...           72</code></pre>
</div>
</div>
<p>Answer:</p>
<p>The new PreSch Count column shows the number of preschools in each planning subzone. The Tampines East subzone in Tampines planning area has the most number of preschools, a total of 72.</p>
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     
   0.00    0.00    4.00    7.09   10.00   72.00 </code></pre>
<pre><code>Simple feature collection with 1 feature and 16 fields 
Geometry type: MULTIPOLYGON 
Dimension:     XY 
Bounding box:  xmin: 39655.33 ymin: 35966 xmax: 42940.57 ymax: 38622.37 
Projected CRS: SVY21 / Singapore TM   
  OBJECTID SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N 
1      189          2 TAMPINES EAST    TMSZ02      N   TAMPINES   
  PLN_AREA_C    REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR 
1         TM EAST REGION       ER 21658EAAF84F4D8D 2014-12-05 41122.55     
    Y_ADDR SHAPE_Leng SHAPE_Area                       geometry 
1 37392.39   10180.62    4339824 MULTIPOLYGON (((42196.76 38...   
  PreSch Count 
1           72</code></pre>
<p>Scenario:</p>
<p>Find the density of pre-school by planning subzone.</p>
<p>Solution:</p>
<p>The <strong>st_area()</strong> is used to derive the area of each planning subzone. Then, the <strong>mutate()</strong> (under dplyr) is used to compute the density.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span>Area <span class="ot">=</span> mpsz3414 <span class="sc">%&gt;%</span> <span class="fu">st_area</span>()</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>mpsz3414 <span class="ot">=</span> mpsz3414 <span class="sc">%&gt;%</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span><span class="sc">/</span>Area <span class="sc">*</span> <span class="dv">1000000</span>)</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   5.154   6.449  10.908  35.602 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">top_n</span>(mpsz3414, <span class="dv">1</span>, <span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 18 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 29501.64 ymin: 28623.75 xmax: 29976.93 ymax: 29362.03
Projected CRS: SVY21 / Singapore TM
  OBJECTID SUBZONE_NO SUBZONE_N SUBZONE_C CA_IND    PLN_AREA_N PLN_AREA_C
1       27          8     CECIL    DTSZ08      Y DOWNTOWN CORE         DT
        REGION_N REGION_C          INC_CRC FMEL_UPD_D  X_ADDR   Y_ADDR
1 CENTRAL REGION       CR 65AA82AF6F4D925D 2014-12-05 29730.2 29011.33
  SHAPE_Leng SHAPE_Area                       geometry PreSch Count
1   2116.095   196619.9 MULTIPOLYGON (((29808.18 28...            7
            Area   PreSch Density
1 196619.9 [m^2] 35.60169 [1/m^2]</code></pre>
</div>
</div>
<p>Answer:</p>
<p>The new PreSch Density column shows the number of preschools per square-kilometres in each planning subzone. The Cecil subzone in the Downtown Core planning area has the highest density of preschools, 35.6019 per square-kilometres.</p>
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    
   0.000   0.000   5.154   6.449  10.908  35.602 </code></pre>
<pre><code>Simple feature collection with 1 feature and 18 fields 
Geometry type: MULTIPOLYGON 
Dimension:     XY 
Bounding box:  xmin: 29501.64 ymin: 28623.75 xmax: 29976.93 ymax: 29362.03 Projected CRS: SVY21 / Singapore TM   
    OBJECTID SUBZONE_NO SUBZONE_N SUBZONE_C CA_IND    PLN_AREA_N PLN_AREA_C 
1       27          8     CECIL    DTSZ08      Y DOWNTOWN CORE         DT         
    REGION_N REGION_C          INC_CRC FMEL_UPD_D  X_ADDR   Y_ADDR 
1 CENTRAL REGION       CR 65AA82AF6F4D925D 2014-12-05 29730.2 29011.33   
    SHAPE_Leng SHAPE_Area                       geometry PreSch Count 
1   2116.095   196619.9 MULTIPOLYGON (((29808.18 28...            7                            Area   PreSch Density 
1 196619.9 [m^2] 35.60169 [1/m^2]</code></pre>
</section>
<section id="point-in-polygon-count-for-airbnb-listings" class="level3">
<h3 class="anchored" data-anchor-id="point-in-polygon-count-for-airbnb-listings">1.9.3 Point-in-Polygon Count for AirBnB Listings</h3>
<p>Scenario:</p>
<p>Find out the number of AirBnB listings in each Planning Subzone.</p>
<p>Solution:</p>
<p>The st_intersects identify AirBnB listings in <code>listings_sf</code> that are in each planning subzone of <code>mpsz3414</code>. The <strong>length()</strong> (under Base R) is used to count the number of listings in each planning subzone. The <strong>top_n()</strong> (under dplyr) is used to obtain details of the planning subzone with the most number of listings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">AirBnB Count</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(mpsz3414, listings_sf))  </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">AirBnB Count</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00    2.00   10.78    9.00  243.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">top_n</span>(mpsz3414, <span class="dv">1</span>, <span class="st">`</span><span class="at">AirBnB Count</span><span class="st">`</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 19 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 30342.65 ymin: 32035.6 xmax: 31453.96 ymax: 33233.11
Projected CRS: SVY21 / Singapore TM
  OBJECTID SUBZONE_NO SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C
1      126          6  LAVENDER    KLSZ06      N    KALLANG         KL
        REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR   Y_ADDR
1 CENTRAL REGION       CR A7A07F328A38B6EF 2014-12-05 30874.41 32569.53
  SHAPE_Leng SHAPE_Area                       geometry PreSch Count
1    3609.15   757907.6 MULTIPOLYGON (((31389.56 32...            6
            Area   PreSch Density AirBnB Count
1 757907.6 [m^2] 7.916532 [1/m^2]          243</code></pre>
</div>
</div>
<p>Answer:</p>
<p>The new AirBnB Count column shows the number of preschools in each planning subzone. The Lavender subzone in Kallang planning area has the most number of listings, a total of 243.</p>
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     
   0.00    0.00    2.00   10.78    9.00  243.00</code></pre>
<pre><code>Simple feature collection with 1 feature and 19 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 30342.65 ymin: 32035.6 xmax: 31453.96 ymax: 33233.11
Projected CRS: SVY21 / Singapore TM
  OBJECTID SUBZONE_NO SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C       REGION_N REGION_C
1      126          6  LAVENDER    KLSZ06      N    KALLANG         KL CENTRAL REGION       CR
           INC_CRC FMEL_UPD_D   X_ADDR   Y_ADDR SHAPE_Leng SHAPE_Area                       geometry
1 A7A07F328A38B6EF 2014-12-05 30874.41 32569.53    3609.15   757907.6 MULTIPOLYGON (((31389.56 32...
  PreSch Count           Area   PreSch Density AirBnB Count
1            6 757907.6 [m^2] 7.916532 [1/m^2]          243</code></pre>
<p>Scenario:</p>
<p>Find the density of AirBnb listings by planning subzone.</p>
<p>Solution:</p>
<p>The <strong>st_area()</strong> is used to derive the area of each planning subzone. Then, the <strong>mutate()</strong> (under dplyr) is used to compute the density.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>mpsz3414<span class="sc">$</span>Area <span class="ot">=</span> mpsz3414 <span class="sc">%&gt;%</span> <span class="fu">st_area</span>()  </span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>mpsz3414 <span class="ot">=</span> mpsz3414 <span class="sc">%&gt;%</span>   </span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span><span class="sc">/</span>Area <span class="sc">*</span> <span class="dv">1000000</span>)  </span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   5.154   6.449  10.908  35.602 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">top_n</span>(mpsz3414, <span class="dv">1</span>, <span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 19 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 29501.64 ymin: 28623.75 xmax: 29976.93 ymax: 29362.03
Projected CRS: SVY21 / Singapore TM
  OBJECTID SUBZONE_NO SUBZONE_N SUBZONE_C CA_IND    PLN_AREA_N PLN_AREA_C
1       27          8     CECIL    DTSZ08      Y DOWNTOWN CORE         DT
        REGION_N REGION_C          INC_CRC FMEL_UPD_D  X_ADDR   Y_ADDR
1 CENTRAL REGION       CR 65AA82AF6F4D925D 2014-12-05 29730.2 29011.33
  SHAPE_Leng SHAPE_Area                       geometry PreSch Count
1   2116.095   196619.9 MULTIPOLYGON (((29808.18 28...            7
            Area   PreSch Density AirBnB Count
1 196619.9 [m^2] 35.60169 [1/m^2]           23</code></pre>
</div>
</div>
<p>Answer:</p>
<p>The new AirBnB Density column shows the number of listings per square-kilometres in each planning subzone. The People’s Park subzone in the Outram planning area has the highest density of listings, 504.6143 per square-kilometres.</p>
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    
   0.000   0.000   2.328  24.073   8.996 504.614 </code></pre>
<pre><code>Simple feature collection with 1 feature and 20 fields 
Geometry type: MULTIPOLYGON 
Dimension:     XY 
Bounding box:  xmin: 28532.73 ymin: 29140.08 xmax: 29116.96 ymax: 29688.52 Projected CRS: SVY21 / Singapore TM   
OBJECTID SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C       REGION_N REGION_C 
1       34          2 PEOPLE'S PARK    OTSZ02      Y     OUTRAM         OT CENTRAL REGION       CR            
            INC_CRC FMEL_UPD_D   X_ADDR   Y_ADDR SHAPE_Leng SHAPE_Area                       geometry 
1 B4120D23006C932A 2014-12-05 28831.78 29419.65   1822.193   93140.44 MULTIPOLYGON (((29099.02 29...   
  PreSch Count           Area PreSch Density AirBnB Count   AirBnB Density 
1            0 93140.44 [m^2]      0 [1/m^2]           47 504.6143 [1/m^2]</code></pre>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-eda">1.10 Exploratory Data Analysis (EDA)</h2>
<p>The ggplot2 functions can be used to create useful statistical graphs for exploratory data analysis.</p>
<section id="histograms-of-frequency-of-pre-schools-density" class="level3">
<h3 class="anchored" data-anchor-id="histograms-of-frequency-of-pre-schools-density">1.10.1 Histograms of Frequency of Pre-Schools Density</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mpsz3414<span class="sc">$</span><span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpsz3414, </span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>))) <span class="sc">+</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Are pre-school even distributed in Singapore?"</span>,</span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span> <span class="st">"There are many planning sub-zones with a single pre-school, on the other hand, </span><span class="sc">\n</span><span class="st">there are two planning sub-zones with at least 20 pre-schools"</span>,</span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"Pre-school density (per km sq)"</span>,</span>
<span id="cb112-9"><a href="#cb112-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Student Note</em>: Based on both histograms, the density of pre-schools is right-skewed, with outliers at values above 20.</p>
</section>
<section id="scatterplot-of-pre-schools-density-versus-pre-schools-count" class="level3">
<h3 class="anchored" data-anchor-id="scatterplot-of-pre-schools-density-versus-pre-schools-count">1.10.2 Scatterplot of Pre-Schools Density versus Pre-Schools Count</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpsz3414, </span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">PreSch Count</span><span class="st">`</span>, </span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">x=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">PreSch Density</span><span class="st">`</span>)))<span class="sc">+</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill=</span><span class="st">"light blue"</span>) <span class="sc">+</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">""</span>,</span>
<span id="cb113-9"><a href="#cb113-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Pre-school density (per km sq)"</span>,</span>
<span id="cb113-10"><a href="#cb113-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Pre-school count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Hands-on_Ex1_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Student Note</em>: There appears to be a positive correlation between pre-school count and pre-school density.</p>
</section>
<section id="histograms-of-frequency-of-airbnb-listings-density" class="level3">
<h3 class="anchored" data-anchor-id="histograms-of-frequency-of-airbnb-listings-density">1.10.3 Histograms of Frequency of AirBnB Listings Density</h3>
<p><em>Student Note</em>: Based on both histograms, the density of AirBnB listings is right-skewed, with outliers at values above 200.</p>
</section>
<section id="scatterplot-of-airbnb-listings-density-versus-airbnb-listings-count" class="level3">
<h3 class="anchored" data-anchor-id="scatterplot-of-airbnb-listings-density-versus-airbnb-listings-count">1.10.2 Scatterplot of AirBnB Listings Density versus AirBnB Listings Count</h3>
<p><em>Student Note</em>: There appears to be a positive correlation between AirBnB listing count and AirBnB listing density.</p>
<p><span class="smallcaps"><strong>~~~ End of Hands-on Exercise 1A ~~~</strong></span></p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>